// <auto-generated />
namespace StarFarm.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initStarFarm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initStarFarm));
        
        string IMigrationMetadata.Id
        {
            get { return "202108131200351_init StarFarm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
